/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package doutorado.tese.gui;
import doutorado.tese.io.ManipuladorArquivo;
import doutorado.tese.util.Coluna;
import doutorado.tese.util.Constantes;
import doutorado.tese.legenda.LegendaVisualizacao;
import doutorado.tese.util.Metadados;
import doutorado.tese.visualizacao.glyph.GlyphManager;
import static doutorado.tese.visualizacao.glyph.GlyphManager.getShufflerColors;
import doutorado.tese.visualizacao.treemap.Rect;
import doutorado.tese.visualizacao.treemap.TreeMapItem;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLayeredPane;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import net.bouthier.treemapAWT.TMView;

/**
 *
 * @author Anderson
 */
public class MainTeste extends javax.swing.JFrame {

    
    private HashMap<String, Integer> configs;
    private Random rand;
    private String data;
    private int cont = 0;
    
    /**
     * Creates new form Main
     */
    public MainTeste() {
        
        data = "Textura,Cor,Forma,Letra,Numero,Altura,Largura,CorFundo,ViuTextura,ViuCor,ViuForma,ViuLetra,ViuNumero";
        rand = new Random(System.currentTimeMillis());
        configs = new HashMap<>();
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainTeste.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        
        changeConfigs();
        
    }
        
    public void changeConfigs(){
        cont++;
        contadorLabel.setText(cont+" / 100");
        System.out.println("Quantidade: "+cont);
        configs.put("textura", rand.nextInt(Constantes.TIPO_TEXTURA.length));
        configs.put("cor", rand.nextInt(Constantes.getCorGlyphs().length));
        configs.put("forma", rand.nextInt(Constantes.TIPOS_FORMAS_GEOMETRICAS.length-1));
        configs.put("letra", rand.nextInt(Constantes.LETRAS_ALFABETO.length));
        configs.put("numero", rand.nextInt(Constantes.NUMEROS.length));
        configs.put("x", 50);
        configs.put("y", 50);
        int length = rand.nextInt(50) + 50;
        configs.put("width", length - rand.nextInt(45));
        configs.put("height", length - rand.nextInt(45));
        configs.put("coritem", rand.nextInt(Constantes.getCor().length));

        painelEsquerda.setConfigs(configs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        painelEsquerda = new PainelDeTeste();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnConfirm = new javax.swing.JButton();
        checkboxTexture = new javax.swing.JCheckBox();
        checkboxCircle = new javax.swing.JCheckBox();
        checkboxGeometry = new javax.swing.JCheckBox();
        checkboxLetter = new javax.swing.JCheckBox();
        checkboxNumber = new javax.swing.JCheckBox();
        btnSelectAll = new javax.swing.JButton();
        contadorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Treemap Glyphs");

        jSplitPane1.setDividerLocation(800);
        jSplitPane1.setOpaque(false);

        painelEsquerda.setBackground(new java.awt.Color(153, 255, 153));
        painelEsquerda.setOpaque(false);

        javax.swing.GroupLayout painelEsquerdaLayout = new javax.swing.GroupLayout(painelEsquerda);
        painelEsquerda.setLayout(painelEsquerdaLayout);
        painelEsquerdaLayout.setHorizontalGroup(
            painelEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        painelEsquerdaLayout.setVerticalGroup(
            painelEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(painelEsquerda);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextPane1.setText("Which of the visual variables do you identify clearly?");
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPane1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextPane1.setEnabled(false);
        jScrollPane2.setViewportView(jTextPane1);

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        checkboxTexture.setText("Texture");

        checkboxCircle.setText("Circle");

        checkboxGeometry.setText("Geometry");

        checkboxLetter.setText("Letter");

        checkboxNumber.setText("Number");

        btnSelectAll.setText("SelectAll");
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        contadorLabel.setText("0/100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelectAll)
                            .addComponent(checkboxNumber)
                            .addComponent(checkboxLetter)
                            .addComponent(checkboxGeometry)
                            .addComponent(checkboxCircle)
                            .addComponent(checkboxTexture)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkboxTexture)
                .addGap(18, 18, 18)
                .addComponent(checkboxCircle)
                .addGap(18, 18, 18)
                .addComponent(checkboxGeometry)
                .addGap(18, 18, 18)
                .addComponent(checkboxLetter)
                .addGap(18, 18, 18)
                .addComponent(checkboxNumber)
                .addGap(46, 46, 46)
                .addComponent(btnSelectAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if(cont > Constantes.LIMITE_TESTES){
            PrintWriter writer = null;
            try {
                File file = new File("result.txt");
                writer = new PrintWriter(new BufferedWriter(new FileWriter(file)));
                writer.print(data);
                writer.flush();
                writer.close();
                System.exit(0);
                
            } catch (IOException ex) {
                Logger.getLogger(MainTeste.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                writer.close();
            }
        }
        
        data += "\n"+configs.get("textura")
                +","+configs.get("cor")
                +","+configs.get("forma")
                +","+configs.get("letra")
                +","+configs.get("numero")
                +","+configs.get("height")
                +","+configs.get("width")
                +","+configs.get("coritem")
                +","+(checkboxTexture.isSelected() ? 1 : 0)
                +","+(checkboxCircle.isSelected() ? 1 : 0)
                +","+(checkboxGeometry.isSelected() ? 1 : 0)
                +","+(checkboxLetter.isSelected() ? 1 : 0)
                +","+(checkboxNumber.isSelected() ? 1 : 0);
        
        
        
            checkboxTexture.setSelected(false);
            checkboxCircle.setSelected(false);
            checkboxGeometry.setSelected(false);
            checkboxLetter.setSelected(false);
            checkboxNumber.setSelected(false);
        
        
        changeConfigs();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        checkboxTexture.setSelected(true);
        checkboxCircle.setSelected(true);
        checkboxGeometry.setSelected(true);
        checkboxLetter.setSelected(true);
        checkboxNumber.setSelected(true);
    }//GEN-LAST:event_btnSelectAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frame = new MainTeste();
                frame.setVisible(true);

            }
        });
    }
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JCheckBox checkboxCircle;
    private javax.swing.JCheckBox checkboxGeometry;
    private javax.swing.JCheckBox checkboxLetter;
    private javax.swing.JCheckBox checkboxNumber;
    private javax.swing.JCheckBox checkboxTexture;
    private javax.swing.JLabel contadorLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel painelEsquerda;
    // End of variables declaration//GEN-END:variables
    */
    
   private javax.swing.JButton btnConfirm;
    private javax.swing.JCheckBox checkboxCircle;
    private javax.swing.JCheckBox checkboxGeometry;
    private javax.swing.JCheckBox checkboxLetter;
    private javax.swing.JCheckBox checkboxNumber;
    private javax.swing.JCheckBox checkboxTexture;    
    private javax.swing.JButton btnSelectAll;    
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane jTextPane1;
    private PainelDeTeste painelEsquerda;
    private javax.swing.JLabel contadorLabel;
    
    static MainTeste frame;    
    private ManipuladorArquivo manipulador;

}
