/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doutorado.tese.gui;

import doutorado.tese.util.Constantes;
import doutorado.tese.visualizacao.glyph.GlyphManager;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.util.HashMap;

/**
 *
 * @author Elvis (LABVIS)
 */
public class PainelDeTeste extends javax.swing.JPanel {

    
    
    private HashMap<String, Integer> configs;
    
    
    /**
     * Creates new form PainelDeTeste
     */
    public PainelDeTeste() {
        configs = new HashMap<>();
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2d = (Graphics2D) g;
        g2d.setColor(Color.decode(Constantes.getCor()[configs.get("coritem")]));
        g2d.fillRect(configs.get("x"),configs.get("y"),configs.get("width"),configs.get("height"));
        g2d.setColor(Color.BLACK);

        g2d.drawRect(configs.get("x"),configs.get("y"),configs.get("width"),configs.get("height"));
        GlyphManager manager = new GlyphManager();              
        Rectangle bounds = new Rectangle(configs.get("x"), configs.get("y"), configs.get("width"), configs.get("height"));
        System.out.println("width: "+configs.get("width") +" height: "+configs.get("height"));
        manager.adicionarTextura(g, bounds, Constantes.TIPO_TEXTURA[configs.get("textura").intValue()]);
        manager.adicionarCorForma(g, bounds, Color.decode(Constantes.getCorGlyphs()[configs.get("cor").intValue()]));
        manager.adicionarFormaGeometrica(g, bounds, Constantes.TIPOS_FORMAS_GEOMETRICAS[configs.get("forma").intValue()]);
        manager.adicionarLetrasAlfabeto(g, bounds,Constantes.LETRAS_ALFABETO[configs.get("forma").intValue()]);
        manager.adicionarNumeros(g, bounds,Constantes.LETRAS_ALFABETO[configs.get("forma").intValue()]+Constantes.NUMEROS[configs.get("forma").intValue()]);
        
    }

    
    public void setConfigs(HashMap<String, Integer> configs){
        this.configs = configs;
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
